### ISSUE TITLE
Purpose of `DiamondInit` contract?

### ISSUE THREAD

**Issue by tess3rac7** [mudgen/diamond-1-hardhat#10]
I don't quite follow how the `DiamondInit` contract fits into this example project. 
- It's like a facet of the diamond (since it uses the diamond's storage) but it's never registered as a facet?
- It's not necessary for setting the diamond's state/calling functions during deployment since we can just as well do that in the diamond's constructor? https://github.com/mudgen/diamond-1-hardhat/blob/10a001c8f0d9e8b71e7e2fd8b5829da8a18f9a57/contracts/Diamond.sol#L35
- It's also not necessary for setting the state/calling functions during upgrades since we can just as well do that when calling `diamondCut`—most likely by using the address of the facet that was just upgraded as the `_init` address? https://github.com/mudgen/diamond-1-hardhat/blob/10a001c8f0d9e8b71e7e2fd8b5829da8a18f9a57/contracts/facets/DiamondCutFacet.sol#L19

So then what is the purpose of `DiamondInit` exactly? Is there a use case that cannot be accomplished without it?

**Comment by mudgen** [comment]
> It's like a facet of the diamond (since it uses the diamond's storage) but it's never registered as a facet?

It is different from a facet in that its function `init` is executed only once to initialize during deployment or an upgrade. Facet functions can be called multiple times.

> It's not necessary for setting the diamond's state/calling functions during deployment since we can just as well do that in the diamond's constructor? 

That is correct. DiamondInit is more for upgrades than deployment, but it can also be used when deploying.

> It's also not necessary for setting the state/calling functions during upgrades since we can just as well do that when calling diamondCut—most likely by using the address of the facet that was just upgraded as the _init address? 

Yes, you are right. 

> So then what is the purpose of DiamondInit exactly?

The purpose is to provide a cleaner way to initialize state during upgrades. DiamondInit makes initialization cleaner in these three ways:
1. The `init` function in DiamondInit does not need to contain any logic to enforce that it is only executed once. The `init` function also does not need to be executed within the context of itself.  So therefore DiamondInit is cleaner. To repeat myself: it is cleaner in these ways: not needing logic to prevent more than one execution and it does not have to be executed within its own context.

You might wonder what I mean by " does not have to be executed within its own context". To illustrate this, I'll give you an example of an NFT facet with an init function. Let's say an NFT facet with an init funciton is created. The functions in the NFT facet are added to a diamond and the diamond called the init function in the NFT facet to initialize data that the facet uses like the name and symbol variables.  Well nothing stops a person from calling the `init` function on the facet directly to add bogus data to the facet.  This doesn't necessarily hurt anything but could be embarrassing or annoying.  The same thing can be done with the init function in the DiamondInit contract but since DiamondInit doesn't have any read-only external functions it doesn't matter,  not like the NFT Facet that returns the name and symbol.   Of course the NFT facet can prevent people from calling the `init` function by ensuring it can only be called once and calling it in the constructor of the NFT facet,  but then again DiamondInit is cleaner because it doesn't have to do that.

> Is there a use case that cannot be accomplished without it?

No, the purpose is to do the same things but cleaner in my opinion. 

2. There may be an upgrade that adds/replace/removes functions from multiple facets. Having a single init function to handle initialization in DiamondCut can be easier than multiple init functions in more than one facet.

3. Keeping init functions out of facets provides some organization since facets will contain functions for diamonds and not something else. Init functions are put in their own contracts. This organization is putting different things in different places.

I would say that DiamondInit is a developer preference, in that some will like it and some will want to do things other ways.

**Comment by tess3rac7** [comment]
Thanks for the thorough explanation @mudgen . I can see your POV re: code organization + one-time execution guarantee for free. Those seem like good merits specifically for upgrades in my view. 

If one chooses to use the DiamondInit pattern, would the expectation be to deploy a new `DiamondInit` contract for each upgrade that requires some routine to be executed as part of the upgrade? So one is trading some additional $$ (`DiamondInit` contract deployment gas cost) for the two merits (code organization + one-time execution guarantee for free)?

**Comment by mudgen** [comment]
@tess3rac7 Yes
